/*
 * Copyright (C) 2021 Parisi Alessandro
 * This file is part of RAW4J (https://github.com/palexdev/RAW4J).
 *
 * RAW4J is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RAW4J is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with RAW4J.  If not, see <http://www.gnu.org/licenses/>.
 */

package io.github.palexdev.raw4j.oauth;

import com.google.gson.JsonElement;
import io.github.palexdev.raw4j.enums.endpoints.URLEnum;
import io.github.palexdev.raw4j.exception.OAuthException;
import io.github.palexdev.raw4j.oauth.base.AbstractOAuthFlow;
import io.github.palexdev.raw4j.oauth.base.OAuthFlow;
import okhttp3.FormBody;
import okhttp3.RequestBody;

import java.time.Instant;
import java.util.UUID;

import static io.github.palexdev.raw4j.json.GsonInstance.fromJson;

/**
 * OAuthFlow for Web Apps and Installed Apps that do not need a logged-in user.
 * <p>
 * (For example an app that starts without a logged-in user, you can use it to explore reddit with this flow,
 * then also offers the possibility of logging-in. In that case you should switch to the {@link OAuthAuthorizationCodeFlow}).
 * <p></p>
 * Extends {@link OAuthAuthorizationCodeFlow} as their behavior is very similar (both offer the possibility to store the retrieved token).
 * <p></p>
 * <b>Note</b> on the {@link #storeAuthInfo()} behavior: if you use the library provided Gson instance to serialize the {@link OAuthInfo} object
 * keep in mind that the resulting JSON will only contain the refresh token as it's not a good idea to save the access token. Of course, you can change
 * this behavior by using another Gson instance, but it is not recommended.
 */
public class OAuthAppOnlyFlow extends OAuthAuthorizationCodeFlow {

    //================================================================================
    // Constructors
    //================================================================================
    protected OAuthAppOnlyFlow() {}

    //================================================================================
    // Override Methods
    //================================================================================

    /**
     * {@inheritDoc}
     * <p></p>
     *
     * Tries to load the OAuthInfo by calling {@link #loadAuthInfo()} if it succeeds and the parsed
     * refresh token is not null gets a new access token by using the refresh token and stores the {@link OAuthInfo}
     * object again by calling {@link #storeAuthInfo()}.
     * <p></p>
     * If loading the token fails for whatever reason, {@link #retrieveAccessToken()} is called and then the {@link OAuthInfo}
     * object is stored.
     */
    @Override
    public void authenticate() throws OAuthException {
        try {
            authInfo = loadAuthInfo();
            if (authInfo != null && authInfo.getRefreshToken() != null) {
                refreshToken();
                storeAuthInfo();
                return;
            }

            logger.debug("Refresh token was invalid, starting full authentication...");
            retrieveAccessToken();
            storeAuthInfo();
        } catch (Exception ex) {
            throw new OAuthException("Authentication failed, cause was: \n" + ex.getMessage());
        }
    }

    /**
     * Retrieves the access token by sending a request to {@link URLEnum#OAUTH_TOKEN_URL} with
     * "?duration=permanent" as a parameter if {@link OAuthParameters#isPermanent()} is true.
     * <p>
     * The request body contains the grant type and the device id generated by {@link #generateDeviceID()}.
     *
     * @throws OAuthException if the returned {@link OAuthInfo} is not valid
     */
    @Override
    protected void retrieveAccessToken() throws OAuthException {
        logger.debug("Retrieving token...");
        RequestBody requestBody = new FormBody.Builder()
                .add("grant_type", URLEnum.OAUTH_APP_ONLY_URL.toString())
                .add("device_id", generateDeviceID())
                .build();

        String url = URLEnum.OAUTH_TOKEN_URL + (parameters.isPermanent() ? "?duration=permanent" : "");
        JsonElement response = post(url, requestBody);
        authInfo = fromJson(response, OAuthInfo.class);
        authInfo.setExpireTime(Instant.now().getEpochSecond() + authInfo.getExpiresIn() - getExpireSecondsOffset());
        if (!authInfo.isValid()) {
            throw new OAuthException("Invalid AuthInfo, check that the specified client parameters are correct");
        }
        authInfo.setPermanent(parameters.isPermanent());
        authInfo.setScopes(parameters.getScopes());
        logger.debug("Token retrieved");
    }

    //================================================================================
    // Methods
    //================================================================================

    /**
     * Generates the device id using {@link UUID#randomUUID()}.
     */
    private String generateDeviceID() {
        return UUID.randomUUID().toString();
    }

    //================================================================================
    // Builders
    //================================================================================

    /**
     * Builder for all OAuthAppOnlyFlows, extends {@link AbstractBuilder}.
     */
    public static class Builder extends AbstractBuilder {
        private final OAuthAppOnlyFlow authManager;

        public Builder() {
            authManager = new OAuthAppOnlyFlow();
        }

        @Override
        protected OAuthFlow getOAuthManager() {
            return authManager;
        }

        /**
         * Initializes the OAuth flow instance of this Builder with the given parameters.
         */
        @Override
        public AbstractOAuthFlow from(OAuthParameters parameters) {
            setAuthDataFrom(parameters);
            authManager.setParameters(parameters);
            return authManager;
        }
    }
}
